<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWIN6984194" failures="1" tests="5" name="testRunner.testRunner" time="6.520" errors="0" timestamp="2021-01-25T02:07:04 IST" skipped="0">
  <testcase classname="testRunner.testRunner" name="runScenario" time="1.650"/>
  <system-out/>
  <testcase classname="testRunner.testRunner" name="runScenario" time="0.210">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at stepdefinitions.GetWeatherDetails.verify_count_is_equal_to_for_the_given_place(GetWeatherDetails.java:85)
at âœ½.Verify "WEOID" count is Equal to 1 for the given place(file:///C:/BDD_Workspace/MetaWeatherAPITestProject/src/test/resources/AppFeatures/VerifyPlaceID.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testRunner.testRunner" name="runScenario" time="3.476"/>
  <system-out/>
  <testcase classname="testRunner.testRunner" name="runScenario" time="0.802"/>
  <system-out/>
  <testcase classname="testRunner.testRunner" name="runScenario" time="0.382"/>
  <system-out/>
</testsuite> <!-- testRunner.testRunner -->
